"""
Django settings for python_example project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import datetime
import os
import sys
from pathlib import Path

try:
    from config import config
except ImportError as e:
    print(f"导入配置信息失败: {str(e)}")
    raise e

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-**gjf(f_h)^e32x#fk_)cxzpbq5saxge7*x$skb+*dr4ui)tef'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config.DEBUG

ALLOWED_HOSTS = config.ALLOWED_HOSTS

# Application definition

############################# INSTALLED_APPS #############################

sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    # 添加 common app
    'apps.common',
    'apps.infer',
]

############################# MIDDLEWARE #############################

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'python_example.common.middleware.request.RequestLoggingMiddleware',
    # 添加 全局异常捕获
    'python_example.common.middleware.except.GlobalExceptionMiddleware'
]

ROOT_URLCONF = 'python_example.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'python_example.wsgi.application'

############################# DATABASES #############################

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

os.makedirs(os.path.dirname(config.DB_PATH), exist_ok=True)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': config.DB_PATH,
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = config.LANGUAGE_CODE

# TIME_ZONE = 'UTC'
TIME_ZONE = config.TIME_ZONE

USE_I18N = config.USE_I18N

USE_TZ = config.USE_TZ

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

############################# LOGGING #############################

os.makedirs(os.path.dirname(config.LOG_PATH), exist_ok=True)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} - {message}',
            'style': '{',
        },
        'standard': {
            'format': '%(asctime)s.%(msecs)03d | %(levelname)-7s | %(module)16s:%(lineno)-4d | %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'console': {
            '()': 'colorlog.ColoredFormatter',
            'format': '%(asctime)s.%(msecs)03d | %(log_color)s%(levelname)-7s%(reset)s | %(module)16s:%(lineno)-4d | %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
            'log_colors': {
                'DEBUG': 'cyan',
                'INFO': 'blue',
                'WARNING': 'yellow',
                'ERROR': 'red',
                'CRITICAL': 'red,bg_white',
            },
        }
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'console',
            'level': 'DEBUG',  # 只处理 info 及以上的日志
        },
        'file': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            # 'class': 'python_example.common.logging.handlers.custom_handlers.ReliableTimedRotatingFileHandler',
            # 'class': 'python_example.common.logging.handlers.custom_handlers.MultiProcessSafeTimedRotatingFileHandler',
            'filename': config.LOG_PATH,
            'when': 'midnight',  # 每天零点新建一个日志文件
            'interval': 1,
            'backupCount': config.LOG_BACKUP_COUNT,  # 保留 7 天
            'delay': False,
            'utc': False,
            'atTime': datetime.time(00, 00, 00),
            'formatter': 'standard',
            'encoding': 'utf-8',
            'level': 'DEBUG',  # 处理 debug 及以上的日志
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'DEBUG',
    },
    'loggers': {
        '__main__': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',  # Logger 必须能接收 debug 日志
            'propagate': False,  # 防止冒泡到 root logger
        },
    }
}
