# 自己制作 ultralytics/ultralytics:8.3.234 镜像
FROM pytorch/pytorch:2.5.1-cuda12.1-cudnn9-runtime AS ultralytics-builder
#FROM pytorch/pytorch:2.5.1-cuda12.1-cudnn9-devel AS ultralytics-builder

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_BREAK_SYSTEM_PACKAGES=1 \
    MKL_THREADING_LAYER=GNU \
    OMP_NUM_THREADS=1 \
    TF_CPP_MIN_LOG_LEVEL=3 \
    DEBIAN_FRONTEND=noninteractive \
    TZ=Asia/Shanghai \
    ULTRALYTICS_VERSION=v8.3.234 \
    UV_HTTP_TIMEOUT=60 \
    LANG='en_US.UTF-8' \
    LANGUAGE='en_US:en' \
    LC_ALL='en_US.UTF-8'

ADD https://github.com/ultralytics/assets/releases/download/v0.0.0/Arial.ttf \
    https://github.com/ultralytics/assets/releases/download/v0.0.0/Arial.Unicode.ttf \
    /root/.config/Ultralytics/

RUN sed -i s@/archive.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list && \
    sed -i s@/security.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
    gcc git htop locales vim \
    zip unzip \
    wget curl \
    libgl1 libglib2.0-0 gnupg libsm6  \
    tzdata \
    logrotate && \
    echo "Asia/Shanghai" > /etc/timezone && \
    ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata && \
    locale-gen en_US.UTF-8 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /ultralytics

RUN git clone -b $ULTRALYTICS_VERSION https://github.com/ultralytics/ultralytics.git /ultralytics && \
    sed -i '/^\[http "https:\/\/github\.com\/"\]/,+1d' .git/config && \
    sed -i'' -e 's/"opencv-python/"opencv-python-headless/' pyproject.toml
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n.pt .

RUN pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/ && \
    pip install -U uv && \
    uv --no-cache pip install --system -e "." albumentations faster-coco-eval wandb && \
    rm -rf tmp /root/.config/Ultralytics/persistent_cache.json && \
    rm -rf /root/.cache/uv

FROM ubuntu:22.04 AS tools-builder

ENV GRPCURL_VERSION=1.9.3 \
    GHPROXY="" \
    DEBIAN_FRONTEND=noninteractive

#              ubuntu                   alpine
# tini 安装目录 /usr/bin/tini           /sbin/tini
# gosu 安装目录 /usr/sbin/gosu          /usr/bin/gosu
# grpcurl 安装目录 /usr/bin/grpcurl     只能 golang:alpine->go install 然后 COPY
RUN sed -i s@/archive.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list && \
    sed -i s@/security.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
    tini gosu wget curl tzdata && \
    dpkg-reconfigure -f noninteractive tzdata && \
    ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    wget --no-check-certificate ${GHPROXY}https://github.com/fullstorydev/grpcurl/releases/download/v${GRPCURL_VERSION}/grpcurl_${GRPCURL_VERSION}_linux_amd64.deb && \
    dpkg -i grpcurl_${GRPCURL_VERSION}_linux_amd64.deb

# -plaintext 是不带ssl的
# 如果需要ssl -cacert -key -cert -servername -insecure 等字段即可
HEALTHCHECK --start-period=60s --interval=60s --timeout=3s --retries=3 \
            CMD grpcurl -d '{"xxx":"xxx"}' \
            -proto /path/xxx.proto \
            -plaintext 127.0.0.1:8888 \
            hello.SayHelloService/SayHello || exit 1

FROM ultralytics-builder AS pip-builder

WORKDIR /pip

COPY requirements.txt .

RUN uv --no-cache pip install --system -r requirements.txt && \
    rm -rf /root/.cache/uv && \
    rm -rf /pip

FROM pytorch/pytorch:2.5.1-cuda12.1-cudnn9-runtime AS code-builder

WORKDIR /code

COPY . .

RUN mv /code/docker-entrypoint.sh /docker-entrypoint.sh && \
    rm /code/requirements*.txt && \
    chmod +x /docker-entrypoint.sh

FROM ultralytics-builder AS runner-prepare


RUN yolo settings && \
    python -c "from torchvision.models import ResNet18_Weights, resnet18; model18=resnet18(weights=ResNet18_Weights.DEFAULT);" && \
    printf '%s\n' '#!/bin/sh' 'ls --color=auto -lah "$@"' > /usr/bin/ll && \
    chmod +x /usr/bin/ll

FROM pip-builder AS runner

#创建非 root 用户
RUN groupadd -g 1000 -r appusers && \
    useradd -m -r -u 1000 -g appusers appuser && \
    mkdir -p /home/appuser/myapp && \
    mkdir -p /home/appuser/myapp/db && \
    mkdir -p /home/appuser/myapp/logs && \
    mkdir -p /home/appuser/myapp/uploads && \
    mkdir -p /home/appuser/.config/Ultralytics && \
    mkdir -p /home/appuser/.cache/torch/hub/checkpoints && \
    chown -R appuser:appusers /home/appuser && \
    tee /etc/logrotate.d/myapp <<'EOF'
/home/appuser/myapp/logs/run.log {
    su appuser appusers
    daily
    rotate 30
    missingok
    notifempty
    copytruncate
    delaycompress
    dateext
    dateformat -%Y%m%d
    compress
    create 0644 appuser appusers
    sharedscripts
    noolddir
}
EOF

WORKDIR /home/appuser/myapp

COPY --from=code-builder --chown=appuser:appusers   /code/                                      .
COPY --from=code-builder                            /docker-entrypoint.sh                       /docker-entrypoint.sh
COPY --from=tools-builder                           /usr/bin/tini                               /usr/bin/tini
COPY --from=tools-builder                           /usr/sbin/gosu                              /usr/sbin/gosu
COPY --from=runner-prepare --chown=appuser:appusers /root/.config/Ultralytics/settings.json     /home/appuser/.config/Ultralytics/settings.json
COPY --from=runner-prepare --chown=appuser:appusers /root/.config/Ultralytics/Arial.ttf         /home/appuser/.config/Ultralytics/Arial.ttf
COPY --from=runner-prepare --chown=appuser:appusers /root/.config/Ultralytics/Arial.Unicode.ttf /home/appuser/.config/Ultralytics/Arial.Unicode.ttf
COPY --from=runner-prepare --chown=appuser:appusers /root/.cache/torch/hub/checkpoints/*        /home/appuser/.cache/torch/hub/checkpoints/


ENV ENABLE_DEBUG_LOG=false

USER appuser:appusers

VOLUME /home/appuser/myapp/logs \
       /home/appuser/myapp/db \
       /home/appuser/myapp/config

EXPOSE 8000

ENTRYPOINT ["/usr/bin/tini","--","/docker-entrypoint.sh"]

HEALTHCHECK --start-period=60s --retries=3 --timeout=15s --interval=60s \
    CMD curl -fsSL http://127.0.0.1:8000/ || exit 1

CMD ["serve", "-migrate", "-address", "0.0.0.0:8000","-config","config/gunicorn.config.py"]
