from enum import Enum, unique

@unique
class ModelType(Enum):
    YOLO_DETECT = "YOLO-DETECT"
    YOLO_CLASSIFY = "YOLO-CLASSIFY"
    RESNET18 = "ResNet18"
    RFDETR_DETECT_NANO = "RFDETR-DETECT-NANO"
    RFDETR_DETECT_SMALL = "RFDETR-DETECT-SMALL"
    RFDETR_DETECT_MEDIUM = "RFDETR-DETECT-MEDIUM"
    RFDETR_DETECT_LARGE = "RFDETR-DETECT-LARGE"
